import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { preview } from '../assets';
import { getRandomPrompt } from "../utils/index";
import { FormFields, Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();
  const [Form, setForm] = useState({name: '', prompt: '', photo: ''});
  const [generatingImage, setGeneratingImage] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = () => {

  }

  const handleChange = (e) => {

  }

  const handleSurpriseMe = () => {

  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[2rem]'>Create</h1>
        <p className='mt-2 text-[#666e75] text-[1rem] max-w[500px]'>
          Brwose Through a collection of images generated by DALL-E AI and share them with others
        </p>
      </div>
      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormFields 
            labelName="Your name" 
            type="text" 
            name="name" 
            placeholder="John Doe" 
            // value={form.name} 
            handlechange={handleChange}/>
          <FormFields 
            labelName="Prompt" 
            type="text" 
            name="Prompt" 
            placeholder="an armchair in the shape of an avocado" 
            // value={form.prompt} 
            handlechange={handleChange} 
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}/>
        </div>
      </form>
    </section>
  )
}

export default CreatePost